### PR TITLE
Extended squareMode feature from CameraViewController to EditorViewController

### PR DESCRIPTION
**Pull request by robertibiris**
When I saw the IMGLYCameraViewController had a property for squareMode to take square pictures, I realised this was not yet extended to work in harmony with the IMGLYEditorViewController yet (which can become a problem when users select pre-existing photos from the camera Roll, which can have any other aspect ratio). So i decided to implement this, and so, here it is =)

-I performed changes into IMGLYCropEditorViewController, so that it can be configured to force one of its available IMGLYSelectionModes (whichever is desired, not only the .OneToOne selectionMode which is the one used for squaring images)

-Based on that, I've updated IMGLYMainEditorViewController to use this ability to force Cropping Modes, and added the property squareMode (same found in CameraController and CameraViewController classes) so that it forces the .OneToOne selectionMode, thus resulting in squared images (yay! 👏👏)

-finally I've updated the IMGLYCameraViewController class to use this new capability, and configure the MainEditorViewController to use squareMode, whenever the CameraViewController itself uses it.

If you can please release a Newer version with these changes into Cocoapods soon, I'd appreciate it, so I can also update my own project with all the new goodies 💪

Just wanted to add: Thanks for such an AWESOME project guys!

### CODE REVIEW

**Comment by K4stor** [comment]
Hi 

Thanks alot for your hard work !
We are currently devloping an API that allows better customizing. 
One part is that the user can easily choose supported crop modes.

Therefore we need to check if / how your changes may conflict that new API.
We'll keep you updated !

**Comment by robertibiris** [comment]
Cool! thanls for the quick reply! =)
Happy new year BTW 👍

**Comment by sascha** [comment]
@robertibiris: Thanks again for your effort. Unfortunately we were not able to merge your pull request due to the extensive API changes we are currently making. The possibility to limit the allowed crop modes was already planned and being worked on when you submitted the pull request. But we loved the idea to force a crop mode, which is why I've just included that in the 'development' branch. I've also added code that checks if the passed image already has one of the allowed aspect ratios and don't show the crop editor immediately in that case.

To get your desired effect you should configure your `CameraViewController` like this:

    let configuration = Configuration() { builder in
        builder.configureCameraViewController { options in
            options.cropToSquare = true
        }

        builder.configureMainEditorViewController { options in
            options.forceCrop = true
        }

        builder.configureCropEditorViewController { options in
            options.allowedCropActions = [ .OneToOne ]
        }
    }

    let cameraViewController = CameraViewController(configuration: configuration)

This will be part of the 3.0 release, so it's going to take a little more time before we will be able to release it. Sorry about that and again, thanks for your work!

**Comment by robertibiris** [comment]
Thank you for the response. I'm then looking forward to the new release :) i appreciate the effort u guys have made, and the time you've taken to clarify the new API for me. 
Keep up the good work guys!

**Comment by aforty** [comment]
Sorry to bump this but I'm curious when we can expect the 3.0 release.

**Pull request closed without merging**
